/* Generated with Author-it 5.5.255.12761  31/07/2013 11:08:11 */
Page=new Array();Page[0]=new Array("A class set is a collection of intervals. Each interval represents a range of discrete values in a data characteristic. ","Each interval has a name and a range (or number of ranges). The range determines the data values that are represented by the interval name. Each range can be a single discrete value or a range of values defined by a lower and upper value.","Class sets have many applications but are predominantly used for scoring elements in scorecards and for segmentation.","An example of a class set is displayed below: ","Classing used for scoring","A scorecard will allocate score values to each interval in a class set used in the scorecard. The scores are added together to provide a total score once all the elements within a scorecard have been processed. You may therefore group together data that requires the same score to be allocated. For example, using the Residential Status characteristic you may class as follows:","Internal Name","Range","Score allocated in Scorecard: 'Risk Scorecard'","Home Owner","&quot;HO&quot;","20","Tenant","&quot;T&quot;","-10","Living with Parents","&quot;LWP&quot;","15","Not Given, Others","&quot;NG&quot;; &quot;X&quot;","0","Classing used for segmentation","For segmentation purposes you would group data in the way you wish to process it. Segments of the population relating to each interval are routed down different pathways, allowing different actions/treatments to be applied to them. For example, using the Residential Status characteristic you may class as follows:","Interval Name","Range","Leads to Action","Home Owner","&quot;HO&quot;","Send Mail Pack A","Tenant, Living with Parents","&quot;T&quot;; &quot;LWP&quot;","Send Mail Pack B","Not Given, Others","&quot;NG&quot;; &quot;X&quot;","No mailing","Class sets overview","Classsetsoverview.htm");
Page[1]=new Array("The class set editor screen consists of:","Tool bar with options designed to assist you in creating and editing intervals. ","Characteristic - a browse button accesses the Characteristic Chooser dialog which enables you to search for a characteristic from the available Logical Data Sources. The discrete values in the selected characteristic are used to define the ranges for the intervals.","Properties - displays the type and length of the selected characteristic.","The interval table is where a row is created for each interval required in the class set. Each interval must have a unique name and a range. The range is the discrete value(s) in the selected characteristic that are represented by the interval. Right click on a row to add a new row or use the relevant tool bar icon.","Name - a unique name for an interval.","Range - the discrete values for the interval. ","Helper - clicking on the icon@ launches the Range Helper dialog to assist you in entering the required range of values for the interval.","Class set editor","Classseteditor.htm");
Page[2]=new Array("The class set tool bar is designed to assist you in editing the class set intervals.","@  Test - Launches the interactive tester for the class set. ","@  Clear all intervals from model - removes all intervals from the class set.","@  Delete Interval - removes the selected interval from the class set.","@  Add Interval - appends a new interval row to the intervals list.","@  Insert Interval - adds an new interval to the interval list above the selected interval row.","@  Split Selected Intervals - applicable to intervals that have multiple ranges. Creates a separate interval for each range.","@  Combine selected intervals - creates a single interval that represents all the values from the selected intervals (as multiple ranges). The original intervals are removed. The resulting interval is named the same as the first interval in the list of selected intervals.","@  Set all interval names to default - changes the name of each interval to match the range description for the interval. For example the range &gt;=10-&lt;20 may have the name 10 to 20, selecting this option will change the name to &gt;=10-&lt;20.","@  Round all intervals to a specified number of decimal places -  sets the values in each interval range to the specified number of decimal places. You will be prompted to enter a number of decimal places. For example, the range &gt;=10.2054-&lt;20.975, if rounded to 2 decimal places, will be changed to &gt;=10.21-&lt;20.98","This option may be applicable after dividing or splitting intervals as the number of decimal places created for these intervals, in order to achieve the split, may be larger than required.","@  Propagate selected interval -  creates a number of further intervals of the width of the selected interval. You will be prompted to enter the number of new intervals.","@  Split selected interval into a number of new intervals - divides the selected interval into a number of intervals. You will be prompted to enter a number of intervals. It will perform this function as evenly as possible within the limitations of the interval properties.","@  Divide selected interval into a number of fixed width intervals - divides the selected interval into multiple intervals of a selected width. You will be prompted to enter a value for the width. If this cannot be performed evenly then the width of the last interval will be smaller to fit the original interval width.","@  Copy to Excel text format - copies all selected intervals to excel text format. You will then need to paste into an Excel spreadsheet.","@  Paste from Excel text format - pastes copied excel text into the interval table.","Class Set Tool bar","ClassSetToolbar.htm");
Page[3]=new Array("A Class set can be created from the Explorer window. ","You will only be able to add a component type that has been allowed for the selected folder. If it is not allowed it will not be listed and therefore cannot be selected.","To create a class set","From the Explorer window right click at the required folder level and select Add a component.","Select Class set from the list of available components.","In the Create a Component screen enter the name of the class set.","Select the Open new components in component editor check box.","Click on the OK button.<br>The Class set editor will open allowing you to select a characteristic and create intervals.<br>The class set name will be listed in the Explorer window under the selected folder level. The component is identified by the @ icon.","If you do not wish the editor to open, keep the check box de-selected.  From the Explorer window, right click on the class set and select Open. .","A class set can be created as an embedded component from within other components for example scorecards, matrices or segmentation trees.","Create a class set","Createaclassset.htm");
Page[4]=new Array("Once you have created a class set you will need to Open the class set and then edit it to:","Select a characteristic","Create intervals","After creation, intervals can be edited and new intervals can be created from those already created. The options available are:","Move an interval","Insert an Interval","Split Intervals","Propagate a selected interval","Edit a class set","Editaclassset.htm");
Page[5]=new Array("Before you can create any intervals in a class set you must first select a characteristic. The intervals will represent groupings of the discrete data values within the selected characteristic.","To select a characteristic ","Click on the Browse button to select a characteristic.<br>The Select Characteristic dialog will open.","In the Search field @ type the word or part of a word that makes up the name of the characteristic.<br>The Select Characteristic dialog will focus in on a particular characteristic or set of characteristics that match this word.","If the Select Characteristic dialog is displaying the characteristics in a tree view, the logical data source will need to be fully expanded to see all the characteristics that match the word(s).","Select the characteristic you require.","Click on the OK button.","The Select Characteristic dialog closes and the characteristic you have selected is added","All the logical data sources that are available to you are also listed in the Resources window.<br>If you know which logical data source contains the characteristic you require, you can drag and drop the logical data source onto the characteristic box in the Class Set editor.<br>@<br>The Select Characteristic dialog will be displayed with the characteristics contained in the logical data source you have selected listed. Select the characteristic you require.","You can now create the required intervals.","Class set resilience:","Name change: The class set will automatically pick up any name changes that are made in the logical data source","Type change: The class set will assess whether the ranges are still valid, and indicate to the user if the ranges are no longer valid using the following @","Delete characteristic: The characteristic and ranges used in the class set will no longer be valid. The class set will indicate to the user the cause of the problem.<br>@","Select a Class Set Characteristic","SelectaClassSetCharacteristic.htm");
Page[6]=new Array("The Select Characteristic dialog enables the user to either select a single characteristic or multi-select a number of characteristics from within a logical data source using the Ctrl and Shift keys on the users keyboard.","The Select Characteristic dialog allows the user to:","@ - Type a word or part of a word next to the Search icon and the Select Characteristic dialog will focus in on a particular characteristic or set of characteristics.","Using the * wildcard, will search all the available logical data sources to display any characteristic name and logical data source name that contains the text. Matching is not case sensitive, so you could use * to match Applicant.Scores.Risk Score with Scor*risk for example.","@ -The Filter for Data Types icon allows the user to narrow down the range of the characteristics displayed in the browsing area to a specific characteristic type (e.g. string, integer, float, decimal and date).","The list of available logical data sources is altered by the search and filter selections that have been made.","@ - The Column display button allows the user to invoke the characteristic chooser to display the Name, Type, Length and Scale for each characteristic.","@ - The Show Table View icon allows the user to change the display of characteristics from a tree view to a table view.","The main area of the screen lists the available logical data sources and the characteristics held in these.","Select Characteristic dialog","SelectCharacteristicdialog.htm");
Page[7]=new Array("Intervals in a class set represent groupings of discrete values in a data characteristic. The interval can represent a single value or a range of values defined by upper and lower values or combinations of values and/or ranges.","Before you can create intervals you must have first selected a characteristic on which the interval values will be based."," To create class set intervals","Click on the add interval icon@ in the tool bar.  A new row will be added to the table with a default name of 'Interval'.","In the Name column overtype 'Interval' with a unique name. ","Enter a range for the row. The class set editor will not allow you to enter an entry that is not appropriate for the characteristic.","Repeat steps 1 to 3 for each interval required.","For numeric values the range can be a single discrete value or a range of values defined by a lower value and an upper value e.g. 20-30. By default, the lower value is included in the range and the upper value is excluded. When you type in the range you can simply enter lower value-upper value as in the 20-30 example above, and then select enter on the keyboard. Using the default settings this range will then appear as &gt;=20-&lt;30. Alternatively you can type in the operators that determine whether the value(s) are included or excluded. For help on entering range values you can click on the Range Helper icon @ at the end of the row.","For characteristics, ranges should be entered with a ;, e.g. a-g;j;l. The system will amend this as follows &quot;a-g&quot;; &quot;j&quot;; &quot;l&quot;.","You can still edit and move intervals after they have been created.","Create Class Set Intervals","CreateClassSetIntervals.htm");
Page[8]=new Array("Where a range is specified, the lower and upper bounds can be included or excluded from the range. By default the lower bound is included and the upper bound is excluded. Each interval range is represented by an expression. When you simply type in a range (for example 10-20), the default expression is used (for example &gt;=10-&lt;20), where the default is not required the range can be entered in expression format. The lower and upper bound modifiers determine whether the values are included or excluded from the range.","Where an interval represents multiple non-contiguous ranges, each row added in the range helper represents a different range for values.","The following examples show how the ranges can be defined.","Lower value included (&gt;=) in the interval and Upper value excluded (&lt;) from the interval (default for range).<br>For example<br>&gt;=1 - &lt; 5  <br>values 1,2,3,4 will be included in the range.","Both lower and upper bound values excluded (&gt; - &lt;).<br>For example<br>&gt;1 - &lt; 5   <br>values 2,3 and 4 will be included in the range.","Lower bound value excluded and upper bound value included (&gt; - &lt;=).<br>For example<br>&gt; 1 - &lt;= 5<br>values 2,3,4,5 will be included in the range.","Both lower and upper bound values included (&gt;= - &lt;=).<br>For example<br>&gt;= 1 - &lt;= 5<br>values 1,2,3,4,5 will be included in the range.","A single discrete value is also represented as an expression. A lower bound modifier of = is selected and a lower bound value entered. If = is selected, no upper bound value can be entered.","Range Helper","RangeHelper.htm");
Page[9]=new Array("Intervals in a class set represent groupings of discrete values in a data characteristic. The interval can represent a single value or a range of values defined by upper and lower values or combinations of values and/or ranges.","HI and LO values","HI and LO are key words that can be used in class set definitions and can be used to ensure that all values that can be passed into the class set are handled appropriately.","HI represents the highest possible value and is only valid as the high bound in a range. For example:","&gt;0 -&nbsp; HI encompasses any positive number no matter how large or small","&gt;= &quot;B&quot; - HI encompasses &quot;B&quot; or any text that alphabetically comes after B","LO represents the lowest possible value and is only valid as the low bound in a range. For example:","LO- &lt; 0 encompasses any negative number no matter how large or small","LO - =&lt; &quot;B&quot; encompasses &quot;B&quot; or any text that alphabetically comes before B","Since HI and LO are not actual values, &nbsp;the &lt;, &lt;=, &gt; and &nbsp;&gt;= notation is not used in the range definition","Empty strings","Empty Strings can be represented in class set ranges by using &quot;&quot;. For example:","&quot;&quot; Will match the empty String explicitly.","&gt;=&quot;&quot; - &lt;=&quot;B&quot; will match the empty String, the Letter &quot;B&quot; and anything between","Because the empty string will always come alphabetically before anything except LO, it would normally only appear as the high bound in the range &nbsp;LO-&lt;=&quot;&quot;. This is equivalent to the range &quot;&quot;.","HI and LO Values and Empty Strings","HIandLOValuesandEmptyStrings.htm");
Page[10]=new Array("Once class set intervals have been created, it is possible to move the order in which they are listed in the class set. ","The order in which the intervals are listed in the class set is the order in which they are displayed/processed when the class set is used. ","To move an interval","Click on the row number for the required interval. The interval will be marked with a green arrow:<br>@","Drag and drop to the required position. In the example below the interval LO-&lt;18 has been dragged from position 1 and dropped into position 3:<br>@","Move an interval","Moveaninterval.htm");
Page[11]=new Array("The order in which the class set intervals are listed is the order in which they will be displayed. It may therefore be necessary to insert an interval into a list of intervals already created.","To insert an interval","Click on an existing interval that you wish to insert above.","Click on the insert interval icon @ on the tool bar. ","A new interval will be created above the selected interval.","Insert an interval","Insertaninterval.htm");
Page[12]=new Array("In a numeric class set, you can create a number of new intervals of the same range width as an existing interval by using Propagate.","For example, if you select to propagate the interval &gt;=10-&lt;20, to create 3 new intervals, this will create:<br>&gt;=20-&lt;30<br>&gt;=30-&lt;40<br>&gt;=40-&lt;50","To propagate an interval","Select the interval you wish to propagate.","Click the Propagate selected intervals icon@ on the tool bar.","Enter the required number of new intervals in the Propagating into N intervals dialog.<br> @","Click the OK button.","The entered number of intervals will be created and listed under the original interval in the list.","Propagate selected interval","Propagateselectedinterval.htm");
Page[13]=new Array("If you have a number of intervals that have continuous ranges, you can combine the ranges into a single interval. You may wish to do this for scoring where modeling has determined that the ranges are to be scored the same or for segmentation where the treatment is to be the same for the different ranges.","To combine selected intervals","Select the first interval in the list of intervals to be combined and drag the mouse down over the other intervals. Alternatively click on the required intervals whilst holding down the CTRL key on the keyboard.<br>The selected intervals will be highlighted and the rows marked with a green arrow:<br>@","Click the Combine intervals icon @ on the tool bar.","A single interval will be created that represents all the values from the selected intervals (as multiple ranges). The original intervals are removed. The resulting interval is named the same as the first interval in the list of selected intervals:<br>@","Combine selected intervals","Combineselectedintervals.htm");
Page[14]=new Array("Where a single interval represents a number of ranges of values it is possible to split the interval so that each range is represented by a separate interval. This is the opposite functionality to combining intervals. ","To split an interval containing multiple ranges","Click on an interval that has a number of ranges defined for it.<br>@","Click on the split intervals icon @ on the tool bar.","The interval will be split with a separate interval created for each range:<br>@","The class set editor uses the ranges of the original interval to produce the names for the new intervals.","Split an interval","Splitaninterval.htm");
Page[15]=new Array("Where you have an interval that has a range of values it is possible to split the interval into a number of new intervals. Each of the new intervals will represent the same fraction of the original range of values. This function will be performed as evenly as possible within the limitations of the interval properties.","For example, if you select to split the interval &gt;=10-&lt;20 into 4 intervals this will create the following intervals:<br>&gt;=10-&lt;12.5<br>&gt;=12.5-&lt;15<br>&gt;=15-&lt;17.5<br>&gt;=17.5-&lt;20 - assuming that the decimal places are allowed. <br>If decimal places was set to 0 then the intervals would be as follows:<br>&gt;=10-&lt;13<br>&gt;=13-&lt;15<br>&gt;=15-&lt;18<br>&gt;=18-&lt;20"," To split an interval into a number of new intervals","Click in the range cell of the interval with a single range of values.","Click in the split into n intervals icon @  on the tool bar.","Enter the required number of new intervals:<br>@","Click on the OK button.","The class set editor uses the ranges of the original interval to produce the names for the new intervals.","Split an interval into a number of new intervals","Splitanintervalintoanumberofnewintervals.htm");
Page[16]=new Array("If you have an interval with a numeric range it is possible to divide this interval into multiple intervals each with the same width. If the selected width does not allow the operation to be performed evenly then the width of the last interval will be smaller to fit the original interval width.","For example, if you select to split the interval &gt;=10-&lt;20 into intervals of width 3 this will create the following intervals:<br>&gt;=10-&lt;13<br>&gt;=13-&lt;16<br>&gt;=16-&lt;19<br>&gt;=19-&lt;20.","To divide an interval into new intervals of fixed width","Click on the required interval","Click on the divide intervals into new fixed width intervals icon @ on the tool bar.","Enter the width of the new intervals:<br>@","Click on the OK button.","The class set editor uses the ranges of the original interval to produce the names for the new intervals.","Divide interval into new fixed width intervals","Divideintervalintonewfixedwidthintervals.htm");
Page[17]=new Array("Once the user has successfully created a class set, the user will be able to test it using the Batch or Interactive Tester. ","The user can test a class set either by manually typing in data for the input characteristics referenced in the class set or by performing a test against a known data source.","To perform an interactive test","To test a class set manually by entering data into the relevant fields for the input characteristics, use the Interactive Tester.","To perform a batch test","To test a class set using data from a .csv file, from the Explorer window, right click on the component and select New Test Project to use the Batch Tester.","Test a class set","Testaclassset.htm");
var PageCount=18;

function search(SearchWord){
var Result="";
var NrRes=0;
Result='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n';
Result+="<html>\n";
Result+="<head>\n";
Result+="<title>Search Results</title>\n";
Result+="<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n";
Result+='<script language="javascript" type="text/javascript" charset="UTF-8" src="dhtml_search.js"></script>\n';
Result+='<link rel="stylesheet" type="text/css" href="stylesheet.css">\n';
Result+="<style type='text/css'>\n";
Result+=".searchDetails {font-family:verdana; font-size:8pt; font-weight:bold}\n";
Result+=".searchResults {font-family:verdana; font-size:8pt}\n";
Result+="</style>\n";
Result+="</head>\n";
Result+="<body onload='javascript:document.SearchForm.SearchText.focus()'>\n";
Result+='<table class="searchDetails" border="0" cellspacing="0" cellpadding="2" width="100%">\n';
Result+='<tr><td>Enter a keyword or phrase</td></tr>';
Result+='<tr><td>';
Result+='<form name="SearchForm" action="javascript:search(document.SearchForm.SearchText.value)">';
if(SearchWord.length>=1){
   while(SearchWord.indexOf("<")>-1 || SearchWord.indexOf(">")>-1 || SearchWord.indexOf('"')>-1){
       SearchWord=SearchWord.replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;");
   }
}
Result+='<input type="text" name="SearchText" size="25" value="' + SearchWord + '" />';
Result+='&nbsp;<input type="submit" value="&nbsp;Go&nbsp;"/></form>';
Result+='</td></tr></table>\n';

if(SearchWord.length>=1){
   SearchWord=SearchWord.toLowerCase();
   this.status="Searching, please wait...";
   Result+="<table border='0' cellpadding='5' class='searchResults' width='100%'>";
   for(j=0;j<PageCount;j++){
       k=Page[j].length-1;
       for(i=0;i<k;i++){
           WordPos=Page[j][i].toLowerCase().indexOf(SearchWord);
           if(WordPos>-1){
               FoundWord=Page[j][i].substr(WordPos,SearchWord.length);
               NrRes++;
               Result+="<tr><td>";
               Result+="<a target='BODY' href='"+Page[j][k]+"'>"+Page[j][k-1].replace(FoundWord,FoundWord.bold())+"</a><br/>\n";

               if(i<k-1){
                   if(Page[j][i].length>350){
                       Result+="..."+Page[j][i].substr(WordPos-100,200+FoundWord.length).replace(FoundWord,FoundWord.bold())+"...\n";
                   }
                   else{
                       Result+=Page[j][i].replace(FoundWord,FoundWord.bold())+"\n";
                   }
               }
               Result+="</td></tr>";
               break;
           }
       }
   }
   Result+="</table>";
   Result+="<p class='searchDetails'>&nbsp;" + NrRes + " result(s) found.</p>";
}

Result+="</body></html>";
this.status="";
this.document.open();
this.document.write(Result);
this.document.close();
}