/* Generated with Author-it 5.5.255.12761  31/07/2013 15:17:51 */
Page=new Array();Page[0]=new Array("The Input Data Connection provides an interface between logical data sources and external physical data sources. Users can:","Select an external database table or CSV file","Map logical characteristics from the published logical data sources to an equivalent on the physical data repository","use the Input Data Connection's Automap, that performs exact matching as well as some degree of &quot;fuzzy&quot; matching that the user can accept or not as required","The Input Data Connection component will be used as input to other components that require access to a physical data source. In the case of Test Project, for example, an input data connection configured for use with a database table can be used as the source of test case data. ","All data configuration and characteristic mappings are maintained when exporting and importing input data connection components and when creating and applying templates that include input data connections. Summary and detailed reports will include information about the data connection and configured mappings.","Input Data Connection overview","InputDataConnectionoverview.htm");
Page[1]=new Array("The Input Data Connection editor enables the user to configure the details of data storage, and to configure a set of logical to physical relationships between the published logical data sources and physical data names taken from the defined data source.","By default, the characteristics metadata in all tables or trees on this screen are limited to name only; by clicking on the Column Display button, the user can display other columns as well. The choice of columns presented depends on the table or tree; the following example is for Logical Characteristics:","Note: In the case of the Physical Characteristics table the type, length and scale columns will only be present for CSV file data source types with associated ESV files.","Horizontal Scroll - select to enable/disable horizontal scrolling for the selected table or tree. Horizontal scrolling is useful when multiple columns are displayed.","Pack All Columns - select to resize each displayed column to accommodate the contents of its longest row (ie, the contents of each column entry is displayed in full).","Pack Selected Column - select to resize the selected column to accommodate the contents of its longest row (ie, the contents of each entry in the selected column is displayed in full). To select a column, click on any column entry. Note that this does not work for all tables.","The Input Data Connection editor consists of:","Data source selection","Logical characteristics selection","Physical characteristics selection","Mapped characteristics selection","Input Data Connection editor","InputDataConnectioneditor.htm");
Page[2]=new Array("Data Location &#8211; click on Select to identify the data source type, and to locate and select the file or database table to use as the data source.","Data source selection","Datasourceselection.htm");
Page[3]=new Array("Logical Characteristics &#8211; logical characteristics tree/table displays all the logical data sources that are published to the node in the system composition where the input data connection component has been created. Use the filters to identify the logical data source characteristics to map to the physical characteristics in the data file or database table. ","@ Select Logical Data Sources &#8211; select to limit the number of logical data sources displayed.","@ Show Table View &#8211; toggle display of logical characteristics between tree or table view. The table view shows the full characteristic name, including path name:","Logical characteristics selection","Logicalcharacteristicsselection.htm");
Page[4]=new Array("The Logical Data Sources Selector dialog enables the user to limit the number of logical data sources displayed in the Logical Characteristics window. ","Click the Select tick mark next the logical data set name to select/deselect the logical data set.","@ Select all - click to select all logical data sets.","@ Un-select all - click to deselect all logical data sets.","Only those logical data sources that are ticked will appear in the list for mapping.","Logical Data Sources Selector dialog","LogicalDataSourcesSelectordialog.htm");
Page[5]=new Array("Physical Characteristics &#8211; physical characteristics table displays all the physical characteristics in the data file or database table. Use the filter to identify the physical characteristics to map to the logical data source characteristics. ","Physical characteristics selection","Physicalcharacteristicsselection.htm");
Page[6]=new Array("Mapped Characteristics - use the mapping buttons to map the logical data characteristics to the physical characteristics.","@ Automap &#8211; automatically tries to map characteristics from the logical data source to the set of physical characteristics in the data file or database table.","@ Map &#8211; map characteristics from the logical data source to the set of physical characteristics manually.","@ Unmap &#8211; unmap mapped characteristics individually. ","@ Unmap All &#8211; unmap all mapped characteristics.","Valid - a validation warning/error will be shown if the logical and physical data types are not compatible.","Mapped characteristics selection","Mappedcharacteristicsselection.htm");
Page[7]=new Array("An input data connection can be created from the Explorer window. ","You will only be able to add a component type that has been allowed for the selected folder. If it is not allowed it will not be listed and therefore cannot be selected. ","To create an input data connection","From the Explorer window right click at the required folder level and select Add component.","Select Input Data Connection.","In the Create component dialog enter the name of the input data connection.","If you wish to have the new component display in the Main editor on creation, ensure that the Open new components in component editor tick box is selected.","Click on the OK button.","The Input Data Connection editor will open allowing you to define the input data connection required.<br>The input data connection name will be listed in the Explorer window under the selected folder level. The component is identified by the @ icon.","If you do not wish the editor to open, de-select the tick box. From the Explorer window select the input data connection and select Open. ","Create an input data connection","Createaninputdataconnection.htm");
Page[8]=new Array("The data source is a CSV file or a database table which stores the physical characteristics of the data set.","To select a CSV file as the data source","From the Input Data Connection editor, click on the Select button in the Data Location section of the editor. The Data Source Selection dialog is displayed.","Check that the data source type is identified as CSV, and click on the  @ button to locate and select the file to use as the data source.","Click the Preview button @ to display a sample of the data set.","Click on the OK button to close the dialog and return to the editor.","The physical characteristics must now be mapped to the logical characteristics, either manually or automatically.","To select a database table as the data source","From the Input Data Connection editor, click on the Select button in the Data Location section of the editor. The Data Source Selection dialog is displayed.","Select Database as the data source type. The dialog reconfigures to prompt for database information.","From the drop down menu, select the Job Server associated with the database, then select the Database to use.","Finally, select the database Table to use as the data source. Note that the Preview button is disabled in this configuration of the dialog.","Click on the OK button to close the dialog and return to the editor. ","The physical characteristics must now be mapped to the logical characteristics, either manually or automatically.","Select a data source","Selectadatasource.htm");
Page[9]=new Array("The Data Source Selection dialog enables the user to select the data source which stores the physical characteristics of the data set. The data source can be either a CSV file or a database table.","When the data source type is a CSV file, the dialog is configured as follows:","Selecting the Preview button in the Data Source Selection dialog opens the Previewer dialog that displays a sample of the data set.","When the data source type is a database table, the dialog is configured as follows:","In this case, the Preview button is disabled.","Data Source Selection dialog","DataSourceSelectiondialog.htm");
Page[10]=new Array("The Previewer dialog displays a sample of the data set:","To display a range of records, type the location of a starting record in the Starting from field and the number of records to fetch in the records field, and click on the fetch by button. ","Click the right arrow button @ to display the next set of records.","Click the left arrow button @ to display the previous set. ","Click the @ button to display records starting from the beginning of the data set.","Previewer dialog","Previewerdialog.htm");
Page[11]=new Array("Once the data source has been selected the user must map the logical characteristics in the logical data sources to the physical characteristics in the data file, either manually as described here, or automatically. This can be carried out in the Input Data Connector editor.","The filters are a useful way to identify those characteristics that should be mapped.","The user can limit the number of logical data sources displayed by clicking on the Select Logical Data Sources button @ to display the Logical Data Sources Selector dialog. The Select Logical Data Sources button can be found in the Input Data Connector editor.","To map characteristics manually","In the Input Data Connector editor, using the filters if necessary, identify and click on a logical characteristic, then identify and click on the physical characteristic with which to map it. The physical characteristics are loaded automatically when the data set is selected.","Click on the Map @ button to map the characteristics. ","If a static or dynamic array element appears anywhere within the hierarchy of the selected logical characteristic, the Select Characteristic Array Element(s) dialog is displayed, enabling you to map static and dynamic arrays.","The mapped characteristics are listed in the Mapped Characteristics table, and the characteristic name disappears from the Logical Characteristics display.","You can specify a group of characteristics all at once by selecting a referenced or embedded logical data model from the characteristics chooser; when you click the Map button, the warning appears: &quot;Selected logical characteristic will result in multiple mappings. Do you want to continue?&quot; Click OK to map all the characteristics in the logical data model to the selected physical characteristic. ","The system checks for mapping validation errors, and displays them in the Mapping table. See the topic Mapping validation for a description of how mapping validation errors can be identified.","Click on Save to save the mapping.","Mapped characteristics can be unmapped individually, using the Unmap @ button, or all together using the Unmap All  @ button. ","Map characteristics manually","Mapcharacteristicsmanually.htm");
Page[12]=new Array("Two sets of filters can be used to help the user find and select characteristics from the set of logical characteristics in the Input Data Connection editor.","@ Filter for Data Types &#8211; Allows the user to limit the display of logical data characteristics to one or more types.","This menu displays extra filters if the input data connection is embedded within a Test Project. The extra filters are:","Execution Input: Only show the logical characteristics that are input characteristics for the component under test","Execution Results: Only show the logical characteristics that are results characteristics for the component under test","@ Filter by Characteristic Name &#8211; Type a word or part of a word next to the Search icon and the Select Characteristic dialog will only display those characteristics whose names match the entered text. Name filtering includes the full logical name of the characteristics; for example, the characteristic Applicant.VIP will show up if the user enters 'A' or 'a' because it's present in 'Applicant'.","A wildcard (*) can be used to match any characteristics or sequence of characteristics, usually with other characters. For example, &#8216;Scor*risk&#8217; will match &#8216;Applicant.Scores.Risk&#8217; or &#8216;Applicant.Scores.Risk2&#8217;","Logical characteristics filters","Logicalcharacteristicsfilters.htm");
Page[13]=new Array("A filter can be used to help the user find and select characteristics from the set of physical characteristics in the Input Data Connection editor.","@ Filter by Characteristic Name &#8211; Type a word or part of a word next to the Search icon and the Select Characteristic dialog will only display those characteristics whose names match the entered text. Name filtering includes the full logical name of the characteristics; for example, the characteristic Applicant.VIP will show up if the user enters 'A' or 'a' because it's present in 'Applicant'.","A wildcard (*) can be used to match any characteristics or sequence of characteristics, usually with other characters. For example, &#8216;Scor*risk&#8217; will match &#8216;Applicant.Scores.Risk&#8217; or &#8216;Applicant.Scores.Risk2&#8217;","Physical characteristics filter","Physicalcharacteristicsfilter.htm");
Page[14]=new Array("The validation checker automatically indicates errors in mapping (data type mismatch, for example). Click on the column display button @ to show all columns in the mapping table to see exactly where the validation fails:","Mapping validation","Mappingvalidation.htm");
Page[15]=new Array("The user can map static and dynamic array logical data characteristics to physical characteristics in the data file, by specifying the indices for the array characteristics. This feature is enabled whenever an array element appears anywhere within the hierarchy of the selected characteristic.","To map a static or dynamic array","In the Input Data Connector editor, using the filters if necessary, identify and click on an array logical characteristic, or a characteristic that has an array element within its hierarchy. For example:","Identify and click on the physical characteristic with which to map it.","Click on the Map @ button to map the characteristics. The Select Characteristic Array Element(s) dialog is displayed, identifying static array characteristics, dynamic array characteristics, and leaf characteristics that appear in the hierarchy:","Specify the index of arrays by typing a value in the Index field. For dynamic arrays, you can type in any number; for static arrays, you must enter a number within the bounds of the size of the static array (as noted in the Type field). ","Click OK to complete the characteristics mapping. ","The mapped characteristics are displayed with the appropriate indices:","Map static and dynamic arrays","Mapstaticanddynamicarrays.htm");
Page[16]=new Array("The Select Characteristic Array Element(s) dialog appears if a static or dynamic array element appears anywhere within the hierarchy of the selected logical characteristic.","The dialog enables the user to enter the index of static and dynamic arrays, to specify the indices for the static or dynamic array. Greyed-out fields cannot be modified.","Characteristic &#8211; provides the full logical characteristic name.","Name &#8211; provides the name of each element in the hierarchy of the selected logical characteristic. Each array has a default value; for dynamic arrays this is [1], while static arrays are initialized with the index that was selected from within the characteristic chooser. In the above example the name has had [1-5] added to it to illustrate the possible index assigned.","Type &#8211; provides the characteristic type: either Static Array, Dynamic Array, or Leaf Characteristic. For static arrays, the size of the static array is listed.","Index &#8211; type in the index of the dynamic or static array. For static arrays, the value entered must be within the bounds of the size of the static array. In the screen shot above, since the Static Array has a size of 5 a range of 1-5 can be added to the index. For either array type, the value entered must be either a single numeric or a single numeric range, or the cell is locked with a red border until the error is corrected: @ (combinations of values are not supported).","Apply To All  - when selecting the multiple array characteristic, you can select this check box to automatically re-use the entered array index values for the same characteristic(s) on any subsequent dialogs.","Select Characteristic Array Element(s) dialog","SelectCharacteristicArrayElement(s)dialog.htm");
Page[17]=new Array("From the Input Data Connection editor, once the data set has been selected the user must map the logical characteristics in the logical data source to the physical characteristics in the data file, either automatically as described here, or manually. Automap will try to match characteristics from the logical data source to the set of physical characteristics. See the discussion for a more detailed description of automapping.","The filters are a useful way to identify those characteristics that should be mapped.","To map characteristics automatically","In the Input Data Connection editor, click on the Automap button @ to map the characteristics. ","The Automap Characteristic dialog is displayed, allowing the user to select which of the suggested mappings to add and which to discard.","Click Accept. The mapped characteristics are listed in the Mapped Characteristics table, and the characteristic names disappear from the Logical Characteristics display.","The system checks for mapping validation errors, and displays them in the Mapping table. See the topic Mapping validation for a description of how mapping validation errors can be identified.","Mapped characteristics can be unmapped individually, using the Unmap button @, or all together using the Unmap All button @. ","Automap characteristics","Automapcharacteristics.htm");
Page[18]=new Array("The Automap Characteristic dialog allows the user to select which of the suggested Logical Name to Physical Name mappings to accept, and which to discard, for inclusion in the Mapped Characteristics table.","Select the mappings to add to the Mapped Characteristics table. Click the Select all button @ to select all suggested mappings; click the Un-select all button @ to deselect all suggested mappings.","Click Accept to add the selected mappings to the table.","Automap Characteristic dialog","AutomapCharacteristicdialog.htm");
Page[19]=new Array("Fuzzy matching","Automap performs exact matching as well as some degree of &quot;fuzzy&quot; matching. For example, the following matches will be offered to the user in the Automap Characteristic dialog to either accept or decline:","Logical Name","Physical Name","Final_Decision","Acc Data CC.Final Decision","Risk Score","Results.Score.Risk Score","NumTimes2DownL3M","Num_Times_2_Dn_L3Months","APPLICANT_AGE","App Data Gen.Main.Age of Applicant","ANNUAL_SALARY","App Data Gen.Main.Total Annual Income ","REVOLVER_SCORE","Results CC.Revolver Scard.Score","Limitations on matching arrays   ","Dynamic array characteristics are not included in the search for matches. Static arrays are included. ","Alternative matches not included","The search will only return the best match for each physical characteristic, not offer alternative matches for the same physical characteristic. To find multiple matches, the user would need to map the first suggestion and then automap again. Logical characteristics will be removed from scope once mapped as they can only be mapped once. ","Order in which mapping occurs","The matching algorithm will work through the logical data sources in the order they are defined in the system composition manager, and through the characteristics in the order they are listed in the logical data sources/logical data models. Therefore the user may see better results from the fuzzy matching depending on how they define their data sources. ","For example, a physical characteristic called AGE would match equally well to App Data Gen.Main.Age as to App Data Gen.Joint.Age. Therefore, if the match is equal, it will return the first match it finds. Thus, if the primary match you want to map is to the Main applicant details, then placing the Main logical data model above the Joint logical data model in the logical data source will produce the desired result. ","Automap characteristics: Discussion","Discussion.htm");
var PageCount=20;

function search(SearchWord){
var Result="";
var NrRes=0;
Result='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n';
Result+="<html>\n";
Result+="<head>\n";
Result+="<title>Search Results</title>\n";
Result+="<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n";
Result+='<script language="javascript" type="text/javascript" charset="UTF-8" src="dhtml_search.js"></script>\n';
Result+='<link rel="stylesheet" type="text/css" href="stylesheet.css">\n';
Result+="<style type='text/css'>\n";
Result+=".searchDetails {font-family:verdana; font-size:8pt; font-weight:bold}\n";
Result+=".searchResults {font-family:verdana; font-size:8pt}\n";
Result+="</style>\n";
Result+="</head>\n";
Result+="<body onload='javascript:document.SearchForm.SearchText.focus()'>\n";
Result+='<table class="searchDetails" border="0" cellspacing="0" cellpadding="2" width="100%">\n';
Result+='<tr><td>Enter a keyword or phrase</td></tr>';
Result+='<tr><td>';
Result+='<form name="SearchForm" action="javascript:search(document.SearchForm.SearchText.value)">';
if(SearchWord.length>=1){
   while(SearchWord.indexOf("<")>-1 || SearchWord.indexOf(">")>-1 || SearchWord.indexOf('"')>-1){
       SearchWord=SearchWord.replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;");
   }
}
Result+='<input type="text" name="SearchText" size="25" value="' + SearchWord + '" />';
Result+='&nbsp;<input type="submit" value="&nbsp;Go&nbsp;"/></form>';
Result+='</td></tr></table>\n';

if(SearchWord.length>=1){
   SearchWord=SearchWord.toLowerCase();
   this.status="Searching, please wait...";
   Result+="<table border='0' cellpadding='5' class='searchResults' width='100%'>";
   for(j=0;j<PageCount;j++){
       k=Page[j].length-1;
       for(i=0;i<k;i++){
           WordPos=Page[j][i].toLowerCase().indexOf(SearchWord);
           if(WordPos>-1){
               FoundWord=Page[j][i].substr(WordPos,SearchWord.length);
               NrRes++;
               Result+="<tr><td>";
               Result+="<a target='BODY' href='"+Page[j][k]+"'>"+Page[j][k-1].replace(FoundWord,FoundWord.bold())+"</a><br/>\n";

               if(i<k-1){
                   if(Page[j][i].length>350){
                       Result+="..."+Page[j][i].substr(WordPos-100,200+FoundWord.length).replace(FoundWord,FoundWord.bold())+"...\n";
                   }
                   else{
                       Result+=Page[j][i].replace(FoundWord,FoundWord.bold())+"\n";
                   }
               }
               Result+="</td></tr>";
               break;
           }
       }
   }
   Result+="</table>";
   Result+="<p class='searchDetails'>&nbsp;" + NrRes + " result(s) found.</p>";
}

Result+="</body></html>";
this.status="";
this.document.open();
this.document.write(Result);
this.document.close();
}